# -*- coding: utf-8 -*-
"""visualizacao_dados

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gqcoa61dz_yC6ZjDdUdDkXvZDcEb3RU3
"""

### imports 
import matplotlib.pyplot as plt


### funcao principal
def main():
  ### dados do arquivo
	arquivo = open("dados/populacao_brasileira.csv").readlines()
	ano = []
	populacao = []

  ### dados do grafico
	titulo = "Crescimento da população brasileira (1980 - 2016)"
	label_ano = "Ano"
	label_populacao = "Populacao x100 000 000"

	### separa os dados do arquivo
	for i in range(1, len(arquivo)):
		linha = arquivo[i].split(";")
		ano.append(int(linha[0]))
		populacao.append(int(linha[1]))
	
	####################################
	### cria o grafico (linha)
	print("Gráfico de linhas:\n")
	plt.plot(ano, populacao)
	plt.title(titulo)
	plt.xlabel(label_ano)
	plt.ylabel(label_populacao)
	plt.show()

	####################################
	### cria grafico (barras)
	print("\n\nGráfico de barras:\n")
	plt.bar(ano, populacao)
	plt.title(titulo)
	plt.xlabel(label_ano)
	plt.ylabel(label_populacao)
	plt.show()

	####################################
	### cria grafico (linhas + barras)
	print("\n\nGráfico de linhas + barras:\n")
	plt.plot(ano, populacao, color='k', linestyle='--')
	plt.bar(ano, populacao, color="#7e7e7e")
	plt.title(titulo)
	plt.xlabel(label_ano)
	plt.ylabel(label_populacao)
	plt.show()

if __name__ == "__main__":
	main()